version: '3.7'

volumes:
    dbData: null
services:
    mongo:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - dbData:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres1@localhost.localhost
            - PGADMIN_DEFAULT_PASSWORD=postgres
        ports:
            - '5050:80'
